name: Commitlint

on:
  pull_request:
    branches:
      - main
      - 'moodle/4.**'

jobs:
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .github/commitlint.config.js
          firstParent: false
